services:
  react:
    image: "alkaponees/amazon-clone-frontend:latest"
    container_name: "frontend"
    ports:
      - "80:80"
    links:
      - restapi

  restapi:
    image: "alkaponees/amazon-clone-backend:latest"
    container_name: "backend"
    expose: 
      - 5034
    ports:
      - "5034:5034"