version: '3'
services:
  amazon-backend:
    build:
      context: ./BackEnd/Amazon-clone       # Path to the directory containing the ASP.NET amazon-backend Dockerfile
      dockerfile: Dockerfile    # Name of the Dockerfile for the amazon-backend
    ports:
      - 5034:5034              # Map port 8000 on the host to port 80 on the container
    depends_on:
      - amazon-frontend               # Ensure the amazon-frontend container is started first

  amazon-frontend:
    build:
      context: ./FrontEnd/myapp     # Path to the directory containing the React amazon-frontend Dockerfile
      dockerfile: Dockerfile    # Name of the Dockerfile for the amazon-frontend
    ports:
      - 3000:3000              # Map port 3000 on the host to port 3000 on the container
    depends_on:
      - amazon-backend 